### ISSUE TITLE
How can I use this on ROS2 foxy like ROS1

### ISSUE THREAD

**Issue by yuan-ge** [zinuok/VINS-Fusion-ROS2#1]
I'm confused about how to use the project in ROS2. I have gone to the built and run the binary file by `vins_node configfile.yaml`. But how can I see the output of the project in rviz2?

**Comment by zinuok** [comment]
hello,
you can run ‘’’rviz2’’’ at ROS2, as you have been used rviz at ROS1. 
As in ROS1, you can check in rviz2 by manually adding vins-related topics.

Sincerely
Jinwoo Jeon

**Comment by zinuok** [comment]
Hello yuan-ge, 

I've just modified my code to run the vins and Rviz2 with the `ros2 run and launch` commands.
Please check [here](https://github.com/zinuok/VINS-Fusion-ROS2#run) for detail.

Sincerely
Jinwoo Jeon
