### ISSUE TITLE
How to run vins using launch file?

### ISSUE THREAD

**Issue by HappySamuel** [zinuok/VINS-Fusion-ROS2#12]
Hi

I notice that the ros2 command for runnig vins has missing the vins_node. 
```
# vins
ros2 run vins $(PATH_TO_YOUR_VINS_CONFIG_FILE)

# Rviz2 visualization
ros2 launch vins vins_rviz.launch.xml
```

I tried and found that it shall be
```ros2 run vins vins_node $(PATH_TO_YOUR_VINS_CONFIG_FILE)```

Back to main question, if i want to run vins using launch file, how shall i do?
i tried `<node pkg="vins" exec="vins_node" name="vins_estimator" output="screen" args="$(find-pkg-share wcr)/config/realsense_stereo_imu_config.yaml"/>`
But end up with error like below:
![Screenshot from 2023-08-22 17-27-46](https://github.com/zinuok/VINS-Fusion-ROS2/assets/18137963/7e736ecc-7c8d-4c8b-923e-38e07c5d00d4)

Best,
Samuel

**Comment by HappySamuel** [comment]
Response to my own question. 

Method for running vins_node in ROS2 launch file is showing as below:
```
<arg name="vins_config" default="/home/$USER/...._ws/src/VINS-FUSION-ROS2/config/realsense_stereo_imu_config.yaml"/>
<executable cmd="ros2 run vins vins_node $(var vins_config)"/>
```

Best,
Samuel

**Comment by huyating99** [comment]
Thanks for your solution. It helps me a lot.
