### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by ZW-PRO** [zinuok/VINS-Fusion-ROS2#15]
采用自己的两个单目相机作为双目使用，最后运行出现waiting for image and imu ......    处于长时间的等待，没有任何进展，请问如何解决？

**Comment by zinuok** [comment]
I'm sorry, but I don't speak Chinese, so please write in English. If you have seen the 'waiting for image and imu ...' error message, check the following:

1) If you're using an IMU, ensure the monocular (or stereo) image and IMU ROS topic names are entered correctly.
2) If you want to run VINS with only stereo images without an IMU, disable use_imu in the yaml file and likewise ensure the topic names are entered correctly.

**Comment by ZW-PRO** [comment]
Thank you very much for your reply. I have solved this problem！
In addition，how to run only the VINS-FUSION visual odometry (VO), without backend and loop detection optimization?can you give me some advices，thank you！

**Comment by zinuok** [comment]
For that purpose, you can just follow the commands in [here](https://github.com/zinuok/VINS-Fusion-ROS2?tab=readme-ov-file#run)
I have to modify some minor bugs in the loop closure part and I will correct that as soon as possible later.

**Comment by ZW-PRO** [comment]
Thank you very much for this excellent work！
