### ISSUE TITLE
Hello, when I run vins_node, the memory keeps increasing, this should not be a normal phenomenon?

### ISSUE THREAD

**Issue by ZW-PRO** [zinuok/VINS-Fusion-ROS2#16]

**Comment by Bob-Eric** [comment]
I think the memory leak was fixed in my commit.
https://github.com/Bob-Eric/VINS-Fusion-ROS2-humble-arm/commit/1663ce894bf86ef91328a5275b74f6a402d60041

![Image](https://github.com/user-attachments/assets/315483e8-2590-4fb3-9f39-49398514cc11)
