### ISSUE TITLE
Trouble with Rviz

### ISSUE THREAD

**Issue by srirama02** [zinuok/VINS-Fusion-ROS2#4]
Hi @zinuok ,

Thank you for adapting VINS-Fusion to ROS2! I am able to run vins on the EuRoC  data set, however I am having trouble visualizing similarly to a previous issue: https://github.com/zinuok/VINS-Fusion-ROS2/issues/2#issuecomment-1200083942

I tried to add the topic but I am having trouble finding the trajectory topic you mentioned in the issue I linked.

These are the available topics:

![image](https://user-images.githubusercontent.com/71669451/212589539-372d3721-8101-4c82-83ff-58b0deea150a.png)

![image](https://user-images.githubusercontent.com/71669451/212589664-50fd0898-1492-41ea-9e73-58c4485bd6ce.png)

Thank you

**Comment by zinuok** [comment]
Dear @srirama02 


Would you add the topic named with 'path' in the above figure? (second topic from the bottom of your picture)
The trajectory topic has the name 'path', not 'trajectory', as can be seen [here](https://github.com/zinuok/VINS-Fusion-ROS2/blob/main/vins/src/utility/visualization.cpp#L37). 
I think I mentioned the name incorrectly in my previous comment. Sorry for the incorrect information.


Thank you
Jinwoo Jeon

**Comment by srirama02** [comment]
Hi,

I tried adding the path topic, but it looks like rviz is unable to read it properly.

![image](https://user-images.githubusercontent.com/71669451/212721699-c693aded-8585-4b71-b525-b4ed0b0d1b30.png)

I echoed the topic(ros2 topic echo /path) and it looks to be publishing so I am not sure what I am doing wrong.

![image](https://user-images.githubusercontent.com/71669451/212722319-0f97a2ce-e255-4a60-b7da-753f39def31d.png)

**Comment by zinuok** [comment]
The fixed frame (in global settings) should be 'world', not 'map'.
This can be found in your second figure where frame_id is set to 'world'.

**Comment by srirama02** [comment]
That fixed the issue. Thank you!

**Comment by HappySamuel** [comment]
Hi @zinuok , @srirama02 

If i want to have it shown under map frame, is there any parameters / remap that can switch the world frame to other frame?

Best,
Samuel

**Comment by RikisuT** [comment]
In mine the world frame isn't there 
What do I do?
