### ISSUE TITLE
<opencv2/cudaoptflow.hpp>

### ISSUE THREAD

**Issue by bonabai** [zinuok/VINS-Fusion-ROS2#6]
Hi, Thanks for putting it in ROS2!
I am giving it a try and setting it up in Ubuntu 20.04 & ROS2 Foxy, however getting errors that can't find "cudaoptflow.hpp"

`/ros2_ws/src/VINS-Fusion-ROS2/vins/src/featureTracker/feature_tracker.h:21:10: fatal error: opencv2/cudaoptflow.hpp: No such file or directory
   21 | #include <opencv2/cudaoptflow.hpp>
`

I saw it recommend use cuda enabled opencv installation, could you share more details about the config? I was just using apt install libopencv-dev && libopencv-contrib-dev, which seems okay for VINFusion on ROS1, but I probably missed something.

cheers!

**Comment by zinuok** [comment]
Hello, 

To GPU be enabled for OpenCV, you have to build and install it manually. 
For that, I referred [here](https://github.com/engcang/vins-application#-ubuntu-2004---this-repo-mainly-targets-ros2-for-ubuntu-2004).

Thank you!

**Comment by bonabai** [comment]
Thanks a lot! I will refer to the link you shared for more details. 
You can close this question for now, and thanks again for putting it together in ROS2.
